//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyApp_BitSolveEntities : DbContext
    {
        public MyApp_BitSolveEntities()
            : base("name=MyApp_BitSolveEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblTypeMaster> tblTypeMasters { get; set; }
        public DbSet<tblCompany> tblCompanies { get; set; }
        public DbSet<tblCountry> tblCountries { get; set; }
        public DbSet<tblCustomer> tblCustomers { get; set; }
        public DbSet<tblItemMaster> tblItemMasters { get; set; }
        public DbSet<tblSupplier> tblSuppliers { get; set; }
        public DbSet<tblUnitMaster> tblUnitMasters { get; set; }
        public DbSet<tblDepartment> tblDepartments { get; set; }
        public DbSet<tblDesignation> tblDesignations { get; set; }
        public DbSet<tblEmployee> tblEmployees { get; set; }
        public DbSet<tblTaxMaster> tblTaxMasters { get; set; }
        public DbSet<tblChangePassword> tblChangePasswords { get; set; }
        public DbSet<tblRoleMaster> tblRoleMasters { get; set; }
        public DbSet<UserRoleMaster> UserRoleMasters { get; set; }
        public DbSet<tblRFQDetail> tblRFQDetails { get; set; }
        public DbSet<tblRFQ> tblRFQs { get; set; }
        public DbSet<tblBidMaster> tblBidMasters { get; set; }
        public DbSet<tblBidDetail> tblBidDetails { get; set; }
        public DbSet<tblMainMenu> tblMainMenus { get; set; }
        public DbSet<tblSubMenu> tblSubMenus { get; set; }
    }
}
