//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompany
    {
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string PinCode { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string TelephoneNo { get; set; }
        public string MobileNo { get; set; }
        public string FaxNo { get; set; }
        public string GSTIN { get; set; }
        public string BankName { get; set; }
        public string BankAccountNo { get; set; }
        public string BankIFSCNo { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public byte[] Logo { get; set; }
        public string LogoPath { get; set; }
    }
}
