//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItemMaster
    {
        public int ItemId { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string Description { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> UOMId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ManufacturedBy { get; set; }
        public string SerialNo { get; set; }
        public string BatchNo { get; set; }
        public string HSN { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
