//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRFQ
    {
        public tblRFQ()
        {
            this.tblRFQDetails = new HashSet<tblRFQDetail>();
        }
    
        public long RfqId { get; set; }
        public string RfqNo { get; set; }
        public Nullable<System.DateTime> RfqDate { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string CompanyName { get; set; }
        public string DeliverTo { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public Nullable<System.DateTime> BidValidUntil { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int createdBy { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string SupplierId { get; set; }
        public Nullable<bool> IsEmailSent { get; set; }
    
        public virtual ICollection<tblRFQDetail> tblRFQDetails { get; set; }
    }
}
