//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUnitMaster
    {
        public int UnitId { get; set; }
        public string Unit { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string abbreviation { get; set; }
    }
}
